apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJkZXYxLmRldm5ldC5ob3BzLndvcmtzOjUwNDMiOnsidXNlcm5hbWUiOiJtYW51IiwicGFzc3dvcmQiOiI4cUdhRzFKejVIMjFsVmYiLCJlbWFpbCI6Im1hbnVAaG9wc3dvcmtzLmFpIiwiYXV0aCI6ImJXRnVkVG80Y1VkaFJ6RktlalZJTWpGc1ZtWT0ifX19"
type: kubernetes.io/dockerconfigjson